baseURL = "https://jukejeew.github.io/sarazian/"
title = "สาระเซียน"
languageCode = "th"
defaultContentLanguage = "th"
defaultContentLanguageInSubdir = false
theme = "PaperMod"
enableGitInfo = true
canonifyURLs = true   # ให้แปะ baseURL ครบทุกลิงก์ เหมาะกับ Project Pages

[[menu.main]]
name = "Posts"
url = "posts/"
weight = 1
[[menu.main]]
name = "Categories"
url = "categories/"
weight = 2
[[menu.main]]
name = "Tags"
url = "tags/"
weight = 3
[[menu.main]]
name = "About"
url = "about/"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"

[params]
siteName = "เพจสาระเซียน"
author = "วัยสนธยา"
description = "☕ ทุกเรื่องราวมีชีวิต"
homeSubtitle = "เล่าเรื่อง → ธุรกิจ → เศรษฐกิจ → ไลฟ์สไตล์"
name = "วัยสนธยา"
about = "นักเขียนมือใหม่บน Debian + ThinkPad"
defaultTheme = "dark"                                       # แก้ "defualtTheme" เป็น "defaultTheme"
readTime = false
ShowReadingTime = false
ShowToc = true
aboutVariant = "full"                                       # "full" | "compact"
articleFooter = "custom"
articleCredit = "show"                                      # "show"   | "hide"
mainSections = ["posts"]

[params.footerNote]
mode = "hide" 													# "show"   | "hide"
title = "หมายเหตุ"
text = "*..."      # เพิ่มข้อความเพื่อให้แสดงผล

[params.credit]
publishedOn = "บทความนี้เผยแพร่บน"
writtenBy = "เขียนโดย"

[params.license]
mode = "hide"													# "show"   | "hide"
style = "copyright"
label = "สัญญาอนุญาต"
holder = "SaraZian"
year = 2025
type = "CC BY-NC-SA 4.0"
url = "https://creativecommons.org/licenses/by-nc-sa/4.0/"

[params.dateform]
LongDate = "Jan 2, 2006"
ShortDate = "Jan 2"
NumDateShort = "2006-01-02"
NumDateLong = "2006-01-02 15:04 -0700"
CopyrightDate = "2006"

[markup]
[markup.highlight]
Classes = false
lineNos = true

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
page = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

[pagination]
pagerSize = 10

[markup.goldmark.renderer]
unsafe = true
