baseURL = "/"
title = "สาระเซียน"
languageCode = "th"
defaultContentLanguage = "th"
defaultContentLanguageInSubdir = false
theme = "PaperMod"
enableGitInfo = true

[[menu.main]]
  name = "Posts"
  url  = "/posts/"
  weight = 1
[[menu.main]]
  name = "Categories"
  url  = "/categories/"
  weight = 2
[[menu.main]]
  name = "Tags"
  url  = "/tags/"
  weight = 3
[[menu.main]]
  name = "About"
  url  = "/about/"
  weight = 4

[taxonomies]
  category = "categories"
  tag      = "tags"

[params]
  siteName = "เพจสาระเซียน"
  author   = "วัยสนธยา"
  description  = "☕ ทุกเรื่องราวมีชีวิต"
  homeSubtitle = "เล่าเรื่อง → ธุรกิจ → เศรษฐกิจ → ไลฟ์สไตล์"
  name  = "วัยสนธยา"
  about = "นักเขียนมือใหม่บน Debian + ThinkPad"
  defualtTheme = "dark"
  readTime     = false
  ShowReadingTime = false
  ShowToc          = true
  # about/footer/credit/license switches
  aboutVariant   = "full"      # "full" | "compact"
  articleFooter  = "slogan"    # "slogan" | "none"
  articleCredit  = "show"      # "show"   | "hide"
  licenseType    = "cc"        # "cc"     | "copyright"
  # customCSS    = ["css/custom.css"]

  [params.shortcodes]
    mode = "simple"   # or "compact"

  [params.footerNote]
    mode  = "show"
    title = "หมายเหตุ"
    text  = ""

  [params.credit]
    publishedOn = "บทความนี้เผยแพร่บน"
    writtenBy   = "เขียนโดย"

  [params.license]
    mode   = "show"
    label  = "สัญญาอนุญาต"
    type   = "CC BY-NC-SA 4.0"
    url    = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
    holder = "Sarazian"

[params.dateform]
  LongDate      = "Jan 2, 2006"
  ShortDate     = "Jan 2"
  NumDateShort  = "2006-01-02"
  NumDateLong   = "2006-01-02 15:04 -0700"
  CopyrightDate = "2006"

[markup]
  [markup.highlight]
    Classes = false
    lineNos   = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home     = ["HTML","RSS"]
  section  = ["HTML","RSS"]
  page     = ["HTML"]
  taxonomy = ["HTML"]
  term     = ["HTML"]

[pagination]
  pagerSize = 10
